### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by stes** [neurallatents/nlb_tools#2]
Hi all, thanks for releasing the tools in this repo! I noticed that currently the LICENSE information is missing, which means that [exclusive copyright](https://choosealicense.com/no-permission/) applies. Is this intended, or are you planning to officially open source this work?

Thanks!

**Comment by joel99** [comment]
Thanks for the notice. We added the MIT license.

**Comment by stes** [comment]
Thanks @joel99 !
