### ISSUE TITLE
Evaluation targets including nan for DMFC_RSG dataset

### ISSUE THREAD

**Issue by yasu-k2** [neurallatents/nlb_tools#5]
Thank you organizers for all the efforts in creating this benchmark.

I was working with the DMFC_RSG dataset and found out that some of the outputs of [`make_eval_target_tensors`](https://github.com/neurallatents/nlb_tools/blob/a2e78c1752e7e922994213de399ed3f2a5610531/nlb_tools/make_tensors.py#L457) includes nan values. The corresponding variables include `eval_spikes_heldout`, `train_behavior`, `eval_behavior`, `psth`. I suspect this has to do with the fix on DMFC_RSG evaluation introduced last November.
I just wanted to make sure if this behavior is as expected or not. I see that the easiest workaround to obtain the validation target is to use part of the `train_spikes_heldout` variable generated with [`make_train_input_tensors`](https://github.com/neurallatents/nlb_tools/blob/a2e78c1752e7e922994213de399ed3f2a5610531/nlb_tools/make_tensors.py#L207) for 'test' phase in place of `eval_spikes_heldout` for 'val' phase.

**Comment by felixp8** [comment]
Yes, this behavior is expected. There are a few things going on here:
* For `eval_spikes_heldout` and `psth`, the NaNs indicate data that lies outside of the Set-Go period. The DMFC_RSG dataset is a bit weird in that the length of the relevant time window varies from trial to trial and it is a behavioral variable that we want to predict. So, we make you model larger fixed windows of data to conceal exactly how long the Set-Go period is, but we only evaluate predictions within the Set-Go period.
* For `train_behavior` and `eval_behavior`, NaNs indicate trials that are considered outliers, which we exclude from the behavior metric. You can read about how these outlier trials were identified in the Methods section of [this paper](https://www.cell.com/neuron/pdfExtended/S0896-6273(19)30562-8) from Hansem Sohn et al., specifically the *"Model Free Analysis of Behavior"* section.

Let me know if you have any further questions!

**Comment by yasu-k2** [comment]
Thank you for your detailed answer!
Now I understand the NaNs arrive from the peculiarity of the DMFC dataset.
I appreciate the paper link for outlier identification. I'll look into it.
