### ISSUE TITLE
feture request - make package available on pypi

### ISSUE THREAD

**Issue by MMathisLab** [neurallatents/nlb_tools#9]
thanks to the devs for this great benchmark and tooling. It would be really helpful if it could indexed on pypi, if the devs would consider? happy to help if useful!

**Comment by felixp8** [comment]
Thanks for the suggestion! It's a great idea, and I'll definitely get to working on it. There are some function names/behaviors that I've wanted to edit for a while but held off on for compatibility, but PyPI versioning solves that so I'll have no more excuses

**Comment by felixp8** [comment]
Package is now [on PyPI](https://pypi.org/project/nlb-tools/), installable with `pip install nlb-tools`!
